service: s3-upload

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  environment:
    SOURCE_BUCKET_NAME: ${env:SOURCE_BUCKET_NAME}
    TARGET_BUCKET_NAME: ${env:TARGET_BUCKET_NAME}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  exclude:
    - "**/*"
    - "!node_modules/**"
    - "!build/**"
    - "**/*.spec.js"
    - "**/*.spec.js.snap"

functions:
  postprocess:
    handler: build/handler.postprocess
    events:
      - s3:
          bucket: ${self:provider.environment.SOURCE_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpg